ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  ACTION_SPACE_CONFIG: "v1"
  AGENT_0:
    # SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR", "SEMANTIC_SENSOR"]
    SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR", "SEMANTIC_SENSOR"]
    HEIGHT: 0.88
    # RADIUS: 0.18
    RADIUS: 0.2
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: True
  SEMANTIC_SENSOR:
    WIDTH: 1280
    HEIGHT: 720
    HFOV: 90
    POSITION: [0, 0.88, 0]
  RGB_SENSOR:
    WIDTH: 1280
    HEIGHT: 720
    HFOV: 90
    POSITION: [0, 0.88, 0]
  DEPTH_SENSOR:
    WIDTH: 1280
    HEIGHT: 720
    HFOV: 90
    MIN_DEPTH: 0.0
    MAX_DEPTH: 10.0
    POSITION: [0, 0.88, 0]
TASK:
  TYPE: ObjectNav-v1
  POSSIBLE_ACTIONS:
    ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT", "LOOK_UP", "LOOK_DOWN"]
  SENSORS: ["GPS_SENSOR", "COMPASS_SENSOR"]
  MEASUREMENTS: ["DISTANCE_TO_GOAL", "SUCCESS", "SPL"]
  SUCCESS:
    SUCCESS_DISTANCE: 1.0

DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  # DATA_PATH: "data/datasets/objectnav/gibson/v1/{split}/{split}.json.gz"
  # EPISODES_DIR: "data/datasets/objectnav/gibson/v1/{split}/"
  # SCENES_DIR: "data/scene_datasets/"
  # DATA_PATH: "/home/junting/Downloads/datasets/habitat_data/datasets/objectnav/gibson/v1/{split}/{split}.json.gz"
  # EPISODES_DIR: "/home/junting/Downloads/datasets/habitat_data/datasets/objectnav/gibson/v1/{split}/"
  # SCENES_DIR: "/home/junting/Downloads/datasets/habitat_data/scene_datasets/"
  DATA_PATH: "/media/junting/SSD_data/habitat_data/datasets/objectnav/gibson/v1/{split}/{split}.json.gz"
  EPISODES_DIR: "/media/junting/SSD_data/habitat_data/datasets/objectnav/gibson/v1/{split}/"
  SCENES_DIR: "/media/junting/SSD_data/habitat_data/scene_datasets/"
